// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Screen_ScreenPraca
void ui_Screen_ScreenPraca_screen_init(void);
void ui_event_Screen_ScreenPraca(lv_event_t * e);
lv_obj_t * ui_Screen_ScreenPraca;
lv_obj_t * ui_ScreenPraca_Panel_PanelViolet;
lv_obj_t * ui_ScreenPraca_Panel_PanelBlue;
lv_obj_t * ui_ScreenPraca_Panel_PanelRed;
lv_obj_t * ui_ScreenPraca_Panel_PanelGreen;
lv_obj_t * ui_ScreenPraca_Panel_PanelYellow;
lv_obj_t * ui_ScreenPraca_Dropdown_DropdownStatus;
lv_obj_t * ui_ScreenPraca_Container_Container1;
void ui_event_ScreenPraca_Button_BtnPraca(lv_event_t * e);
lv_obj_t * ui_ScreenPraca_Button_BtnPraca;
lv_obj_t * ui_ScreenPraca_Label_LabPrc;
void ui_event_ScreenPraca_Button_BtnAwaria(lv_event_t * e);
lv_obj_t * ui_ScreenPraca_Button_BtnAwaria;
lv_obj_t * ui_ScreenPraca_Label_LabAwaria;
void ui_event_ScreenPraca_Button_BtnPomiar(lv_event_t * e);
lv_obj_t * ui_ScreenPraca_Button_BtnPomiar;
lv_obj_t * ui_ScreenPraca_Label_LabPomiar;
void ui_event_ScreenPraca_Button_BtnPrzezbrojenie(lv_event_t * e);
lv_obj_t * ui_ScreenPraca_Button_BtnPrzezbrojenie;
lv_obj_t * ui_ScreenPraca_Label_LabPrzezbrojenie;
void ui_event_ScreenPraca_Button_BtnPrzerwa(lv_event_t * e);
lv_obj_t * ui_ScreenPraca_Button_BtnPrzerwa;
lv_obj_t * ui_ScreenPraca_Label_LabPrc1;
void ui_event_ScreenPraca_Button_BtnBrakObsdy(lv_event_t * e);
lv_obj_t * ui_ScreenPraca_Button_BtnBrakObsdy;
void ui_event_ScreenPraca_Label_LabBrakObsady(lv_event_t * e);
lv_obj_t * ui_ScreenPraca_Label_LabBrakObsady;
void ui_event_ScreenPraca_Textarea_EdOperator(lv_event_t * e);
lv_obj_t * ui_ScreenPraca_Textarea_EdOperator;
void ui_event_ScreenPraca_Keyboard_KeybOperator(lv_event_t * e);
lv_obj_t * ui_ScreenPraca_Keyboard_KeybOperator;
lv_obj_t * ui_ScreenPraca_Button_ButtonChangeScreen;
lv_obj_t * ui_ScreenPraca_Textarea_TextArea1;
lv_obj_t * ui_ScreenPraca_Textarea_TextMQTTData;
// CUSTOM VARIABLES
lv_obj_t * uic_PanelYellow;
lv_obj_t * uic_BtnPraca;
lv_obj_t * uic_BtnPrzerwa;

// SCREEN: ui_Screen_ScreenUstawienia
void ui_Screen_ScreenUstawienia_screen_init(void);
lv_obj_t * ui_Screen_ScreenUstawienia;
void ui_event_ScreenUstawienia_Button_ButtonChangeScreen1(lv_event_t * e);
lv_obj_t * ui_ScreenUstawienia_Button_ButtonChangeScreen1;
lv_obj_t * ui_ScreenUstawienia_Label_LabelBack;
lv_obj_t * ui_ScreenUstawienia_Container_ContainerWifi;
lv_obj_t * ui_ScreenUstawienia_Label_LabelUstawienia;
void ui_event_ScreenUstawienia_Textarea_TextAreaPassword(lv_event_t * e);
lv_obj_t * ui_ScreenUstawienia_Textarea_TextAreaPassword;
void ui_event_ScreenUstawienia_Textarea_TextAreaSSID(lv_event_t * e);
lv_obj_t * ui_ScreenUstawienia_Textarea_TextAreaSSID;
void ui_event_ScreenUstawienia_Button_ButtonConnectWiFi(lv_event_t * e);
lv_obj_t * ui_ScreenUstawienia_Button_ButtonConnectWiFi;
lv_obj_t * ui_ScreenUstawienia_Label_LabelConnectWiFi;
lv_obj_t * ui_ScreenUstawienia_Container_ContainerMQTT;
lv_obj_t * ui_ScreenUstawienia_Label_LabelBrokerMQTT;
void ui_event_ScreenUstawienia_Textarea_TextAdressMQTT(lv_event_t * e);
lv_obj_t * ui_ScreenUstawienia_Textarea_TextAdressMQTT;
void ui_event_ScreenUstawienia_Textarea_TextMQTTPort(lv_event_t * e);
lv_obj_t * ui_ScreenUstawienia_Textarea_TextMQTTPort;
void ui_event_ScreenUstawienia_Textarea_TextMQTTUser(lv_event_t * e);
lv_obj_t * ui_ScreenUstawienia_Textarea_TextMQTTUser;
void ui_event_ScreenUstawienia_Textarea_TextMQTTPassword(lv_event_t * e);
lv_obj_t * ui_ScreenUstawienia_Textarea_TextMQTTPassword;
lv_obj_t * ui_ScreenUstawienia_Container_ContainerStanowisko;
lv_obj_t * ui_ScreenUstawienia_Label_LabelStanowisko;
void ui_event_ScreenUstawienia_Textarea_TextAreaStanowisko(lv_event_t * e);
lv_obj_t * ui_ScreenUstawienia_Textarea_TextAreaStanowisko;
void ui_event_ScreenUstawienia_Keyboard_KeyboardUstawienia(lv_event_t * e);
lv_obj_t * ui_ScreenUstawienia_Keyboard_KeyboardUstawienia;
void ui_event_ScreenUstawienia_Button_ButtonConnectMQTT(lv_event_t * e);
lv_obj_t * ui_ScreenUstawienia_Button_ButtonConnectMQTT;
lv_obj_t * ui_ScreenUstawienia_Label_LabelConnectMQTT;
void ui_event_ScreenUstawienia_Button_ButtonSendMQTTMsg(lv_event_t * e);
lv_obj_t * ui_ScreenUstawienia_Button_ButtonSendMQTTMsg;
lv_obj_t * ui_ScreenUstawienia_Label_LabelSendMQTTMsg;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui_Startevents____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Screen_ScreenPraca(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        _ui_screen_change(&ui_Screen_ScreenUstawienia, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0,
                          &ui_Screen_ScreenUstawienia_screen_init);
    }
}

void ui_event_ScreenPraca_Button_BtnPraca(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_dropdown_set_property(ui_ScreenPraca_Dropdown_DropdownStatus, _UI_DROPDOWN_PROPERTY_SELECTED, 1);
        FuncPraca(e);
        _ui_flag_modify(ui_ScreenPraca_Panel_PanelGreen, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_ScreenPraca_Panel_PanelRed, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_ScreenPraca_Panel_PanelBlue, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_ScreenPraca_Panel_PanelViolet, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_ScreenPraca_Panel_PanelYellow, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_ScreenPraca_Button_BtnAwaria(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_dropdown_set_property(ui_ScreenPraca_Dropdown_DropdownStatus, _UI_DROPDOWN_PROPERTY_SELECTED, 2);
        FuncAwaria(e);
        _ui_flag_modify(ui_ScreenPraca_Panel_PanelRed, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_ScreenPraca_Panel_PanelGreen, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_ScreenPraca_Panel_PanelBlue, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_ScreenPraca_Panel_PanelViolet, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_ScreenPraca_Panel_PanelYellow, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_ScreenPraca_Button_BtnPomiar(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_dropdown_set_property(ui_ScreenPraca_Dropdown_DropdownStatus, _UI_DROPDOWN_PROPERTY_SELECTED, 3);
        FuncPomiar(e);
        _ui_flag_modify(ui_ScreenPraca_Panel_PanelGreen, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_ScreenPraca_Panel_PanelRed, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_ScreenPraca_Panel_PanelBlue, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_ScreenPraca_Panel_PanelViolet, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_ScreenPraca_Panel_PanelYellow, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_ScreenPraca_Button_BtnPrzezbrojenie(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_dropdown_set_property(ui_ScreenPraca_Dropdown_DropdownStatus, _UI_DROPDOWN_PROPERTY_SELECTED, 4);
        FuncPrzezbrojenie(e);
        _ui_flag_modify(ui_ScreenPraca_Panel_PanelGreen, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_ScreenPraca_Panel_PanelRed, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_ScreenPraca_Panel_PanelBlue, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_ScreenPraca_Panel_PanelViolet, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_ScreenPraca_Panel_PanelYellow, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_ScreenPraca_Button_BtnPrzerwa(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_dropdown_set_property(ui_ScreenPraca_Dropdown_DropdownStatus, _UI_DROPDOWN_PROPERTY_SELECTED, 5);
        FuncPraca(e);
        _ui_flag_modify(ui_ScreenPraca_Panel_PanelGreen, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_ScreenPraca_Panel_PanelRed, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_ScreenPraca_Panel_PanelBlue, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_ScreenPraca_Panel_PanelViolet, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_ScreenPraca_Panel_PanelYellow, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_ScreenPraca_Button_BtnBrakObsdy(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_dropdown_set_property(ui_ScreenPraca_Dropdown_DropdownStatus, _UI_DROPDOWN_PROPERTY_SELECTED, 0);
        FuncBrakObsady(e);
        _ui_flag_modify(ui_ScreenPraca_Panel_PanelGreen, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_ScreenPraca_Panel_PanelRed, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_ScreenPraca_Panel_PanelBlue, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_ScreenPraca_Panel_PanelViolet, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_ScreenPraca_Panel_PanelYellow, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_ScreenPraca_Label_LabBrakObsady(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_dropdown_set_property(ui_ScreenPraca_Dropdown_DropdownStatus, _UI_DROPDOWN_PROPERTY_SELECTED, 0);
    }
}

void ui_event_ScreenPraca_Textarea_EdOperator(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_flag_modify(ui_ScreenPraca_Keyboard_KeybOperator, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_ScreenPraca_Keyboard_KeybOperator, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_ScreenPraca_Keyboard_KeybOperator(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        _ui_flag_modify(ui_ScreenPraca_Keyboard_KeybOperator, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_ScreenUstawienia_Button_ButtonChangeScreen1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        _ui_screen_change(&ui_Screen_ScreenPraca, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen_ScreenPraca_screen_init);
    }
}

void ui_event_ScreenUstawienia_Textarea_TextAreaPassword(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_flag_modify(ui_ScreenUstawienia_Keyboard_KeyboardUstawienia, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_keyboard_set_target(ui_ScreenUstawienia_Keyboard_KeyboardUstawienia,
                                ui_ScreenUstawienia_Textarea_TextAreaPassword);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_ScreenUstawienia_Keyboard_KeyboardUstawienia, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_ScreenUstawienia_Textarea_TextAreaSSID(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_flag_modify(ui_ScreenUstawienia_Keyboard_KeyboardUstawienia, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_keyboard_set_target(ui_ScreenUstawienia_Keyboard_KeyboardUstawienia,  ui_ScreenUstawienia_Textarea_TextAreaSSID);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_ScreenUstawienia_Keyboard_KeyboardUstawienia, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_ScreenUstawienia_Button_ButtonConnectWiFi(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        FuncConnectWIFI(e);
    }
}

void ui_event_ScreenUstawienia_Textarea_TextAdressMQTT(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_flag_modify(ui_ScreenUstawienia_Keyboard_KeyboardUstawienia, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_keyboard_set_target(ui_ScreenUstawienia_Keyboard_KeyboardUstawienia,  ui_ScreenUstawienia_Textarea_TextAdressMQTT);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_ScreenUstawienia_Keyboard_KeyboardUstawienia, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_ScreenUstawienia_Textarea_TextMQTTPort(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_flag_modify(ui_ScreenUstawienia_Keyboard_KeyboardUstawienia, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_keyboard_set_target(ui_ScreenUstawienia_Keyboard_KeyboardUstawienia,  ui_ScreenUstawienia_Textarea_TextMQTTPort);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_ScreenUstawienia_Keyboard_KeyboardUstawienia, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_ScreenUstawienia_Textarea_TextMQTTUser(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_basic_set_property(ui_ScreenUstawienia_Container_ContainerMQTT, _UI_BASIC_PROPERTY_POSITION_Y,  -100);
        _ui_flag_modify(ui_ScreenUstawienia_Keyboard_KeyboardUstawienia, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_keyboard_set_target(ui_ScreenUstawienia_Keyboard_KeyboardUstawienia,  ui_ScreenUstawienia_Textarea_TextMQTTUser);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_ScreenUstawienia_Keyboard_KeyboardUstawienia, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_basic_set_property(ui_ScreenUstawienia_Container_ContainerMQTT, _UI_BASIC_PROPERTY_POSITION_Y,  10);
    }
}

void ui_event_ScreenUstawienia_Textarea_TextMQTTPassword(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_flag_modify(ui_ScreenUstawienia_Keyboard_KeyboardUstawienia, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_basic_set_property(ui_ScreenUstawienia_Container_ContainerMQTT, _UI_BASIC_PROPERTY_POSITION_Y,  -100);
        _ui_keyboard_set_target(ui_ScreenUstawienia_Keyboard_KeyboardUstawienia,
                                ui_ScreenUstawienia_Textarea_TextMQTTPassword);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_ScreenUstawienia_Keyboard_KeyboardUstawienia, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_basic_set_property(ui_ScreenUstawienia_Container_ContainerMQTT, _UI_BASIC_PROPERTY_POSITION_Y,  10);
    }
}

void ui_event_ScreenUstawienia_Textarea_TextAreaStanowisko(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_ScreenUstawienia_Keyboard_KeyboardUstawienia,
                                ui_ScreenUstawienia_Textarea_TextAreaStanowisko);
        _ui_flag_modify(ui_ScreenUstawienia_Keyboard_KeyboardUstawienia, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_basic_set_property(ui_ScreenUstawienia_Keyboard_KeyboardUstawienia, _UI_BASIC_PROPERTY_POSITION_Y,  -100);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_ScreenUstawienia_Keyboard_KeyboardUstawienia, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_basic_set_property(ui_ScreenUstawienia_Keyboard_KeyboardUstawienia, _UI_BASIC_PROPERTY_POSITION_Y,  0);
    }
}

void ui_event_ScreenUstawienia_Keyboard_KeyboardUstawienia(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        _ui_flag_modify(ui_ScreenUstawienia_Keyboard_KeyboardUstawienia, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_ScreenUstawienia_Button_ButtonConnectMQTT(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        FuncConnectMQTT(e);
    }
}

void ui_event_ScreenUstawienia_Button_ButtonSendMQTTMsg(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        FuncSendMQTTMsg(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen_ScreenPraca_screen_init();
    ui_Screen_ScreenUstawienia_screen_init();
    ui_Startevents____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen_ScreenPraca);
}
