// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_Screen_ScreenPraca
void ui_Screen_ScreenPraca_screen_init(void);
void ui_event_Screen_ScreenPraca(lv_event_t * e);
extern lv_obj_t * ui_Screen_ScreenPraca;
extern lv_obj_t * ui_ScreenPraca_Panel_PanelGreen;
extern lv_obj_t * ui_ScreenPraca_Panel_PanelRed;
extern lv_obj_t * ui_ScreenPraca_Panel_PanelBlue;
extern lv_obj_t * ui_ScreenPraca_Panel_PanelViolet;
extern lv_obj_t * ui_ScreenPraca_Container_Container1;
void ui_event_ScreenPraca_Button_BtnPraca(lv_event_t * e);
extern lv_obj_t * ui_ScreenPraca_Button_BtnPraca;
extern lv_obj_t * ui_ScreenPraca_Label_LabPrc;
void ui_event_ScreenPraca_Button_BtnAwaria(lv_event_t * e);
extern lv_obj_t * ui_ScreenPraca_Button_BtnAwaria;
extern lv_obj_t * ui_ScreenPraca_Label_LabAwaria;
void ui_event_ScreenPraca_Button_BtnPomiar(lv_event_t * e);
extern lv_obj_t * ui_ScreenPraca_Button_BtnPomiar;
extern lv_obj_t * ui_ScreenPraca_Label_LabPomiar;
void ui_event_ScreenPraca_Button_BtnPrzezbrojenie(lv_event_t * e);
extern lv_obj_t * ui_ScreenPraca_Button_BtnPrzezbrojenie;
extern lv_obj_t * ui_ScreenPraca_Label_LabPrzezbrojenie;
void ui_event_ScreenPraca_Button_BtnBrakObsdy(lv_event_t * e);
extern lv_obj_t * ui_ScreenPraca_Button_BtnBrakObsdy;
void ui_event_ScreenPraca_Label_LabBrakObsady(lv_event_t * e);
extern lv_obj_t * ui_ScreenPraca_Label_LabBrakObsady;
void ui_event_ScreenPraca_Textarea_EdOperator(lv_event_t * e);
extern lv_obj_t * ui_ScreenPraca_Textarea_EdOperator;
void ui_event_ScreenPraca_Keyboard_KeybOperator(lv_event_t * e);
extern lv_obj_t * ui_ScreenPraca_Keyboard_KeybOperator;
extern lv_obj_t * ui_ScreenPraca_Dropdown_DropdownStatus;
extern lv_obj_t * ui_ScreenPraca_Button_ButtonChangeScreen;
// CUSTOM VARIABLES
extern lv_obj_t * uic_BtnPraca;

// SCREEN: ui_Screen_ScreenUstawienia
void ui_Screen_ScreenUstawienia_screen_init(void);
extern lv_obj_t * ui_Screen_ScreenUstawienia;
void ui_event_ScreenUstawienia_Button_ButtonChangeScreen1(lv_event_t * e);
extern lv_obj_t * ui_ScreenUstawienia_Button_ButtonChangeScreen1;
extern lv_obj_t * ui_ScreenUstawienia_Label_LabelBack;
extern lv_obj_t * ui_ScreenUstawienia_Container_ContainerWifi;
extern lv_obj_t * ui_ScreenUstawienia_Label_LabelUstawienia;
void ui_event_ScreenUstawienia_Textarea_TextAreaPassword(lv_event_t * e);
extern lv_obj_t * ui_ScreenUstawienia_Textarea_TextAreaPassword;
void ui_event_ScreenUstawienia_Textarea_TextAreaSSID(lv_event_t * e);
extern lv_obj_t * ui_ScreenUstawienia_Textarea_TextAreaSSID;
extern lv_obj_t * ui_ScreenUstawienia_Button_ButtonConnect;
extern lv_obj_t * ui_ScreenUstawienia_Label_LabelConnect;
extern lv_obj_t * ui_ScreenUstawienia_Container_ContainerMQTT;
extern lv_obj_t * ui_ScreenUstawienia_Label_LabelBrokerMQTT;
void ui_event_ScreenUstawienia_Textarea_TextAdressMQTT(lv_event_t * e);
extern lv_obj_t * ui_ScreenUstawienia_Textarea_TextAdressMQTT;
void ui_event_ScreenUstawienia_Textarea_TextMQTTPort(lv_event_t * e);
extern lv_obj_t * ui_ScreenUstawienia_Textarea_TextMQTTPort;
void ui_event_ScreenUstawienia_Textarea_TextMQTTUser(lv_event_t * e);
extern lv_obj_t * ui_ScreenUstawienia_Textarea_TextMQTTUser;
void ui_event_ScreenUstawienia_Textarea_TextMQTTPassword(lv_event_t * e);
extern lv_obj_t * ui_ScreenUstawienia_Textarea_TextMQTTPassword;
extern lv_obj_t * ui_ScreenUstawienia_Container_ContainerStanowisko;
extern lv_obj_t * ui_ScreenUstawienia_Label_LabelStanowisko;
void ui_event_ScreenUstawienia_Textarea_TextAreaStanowisko(lv_event_t * e);
extern lv_obj_t * ui_ScreenUstawienia_Textarea_TextAreaStanowisko;
void ui_event_ScreenUstawienia_Keyboard_KeyboardUstawienia(lv_event_t * e);
extern lv_obj_t * ui_ScreenUstawienia_Keyboard_KeyboardUstawienia;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui_Startevents____initial_actions0;

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
