// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen_ScreenUstawienia_screen_init(void)
{
    ui_Screen_ScreenUstawienia = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen_ScreenUstawienia, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ScreenUstawienia_Button_ButtonChangeScreen1 = lv_btn_create(ui_Screen_ScreenUstawienia);
    lv_obj_set_width(ui_ScreenUstawienia_Button_ButtonChangeScreen1, 50);
    lv_obj_set_height(ui_ScreenUstawienia_Button_ButtonChangeScreen1, 50);
    lv_obj_set_x(ui_ScreenUstawienia_Button_ButtonChangeScreen1, 210);
    lv_obj_set_y(ui_ScreenUstawienia_Button_ButtonChangeScreen1, 130);
    lv_obj_set_align(ui_ScreenUstawienia_Button_ButtonChangeScreen1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ScreenUstawienia_Button_ButtonChangeScreen1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ScreenUstawienia_Button_ButtonChangeScreen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenUstawienia_Button_ButtonChangeScreen1, lv_color_hex(0xC9C9C9),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenUstawienia_Button_ButtonChangeScreen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScreenUstawienia_Label_LabelBack = lv_label_create(ui_ScreenUstawienia_Button_ButtonChangeScreen1);
    lv_obj_set_width(ui_ScreenUstawienia_Label_LabelBack, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScreenUstawienia_Label_LabelBack, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ScreenUstawienia_Label_LabelBack, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScreenUstawienia_Label_LabelBack, "<-");

    ui_ScreenUstawienia_Container_ContainerWifi = lv_obj_create(ui_Screen_ScreenUstawienia);
    lv_obj_remove_style_all(ui_ScreenUstawienia_Container_ContainerWifi);
    lv_obj_set_width(ui_ScreenUstawienia_Container_ContainerWifi, 155);
    lv_obj_set_height(ui_ScreenUstawienia_Container_ContainerWifi, 155);
    lv_obj_set_x(ui_ScreenUstawienia_Container_ContainerWifi, 10);
    lv_obj_set_y(ui_ScreenUstawienia_Container_ContainerWifi, 10);
    lv_obj_clear_flag(ui_ScreenUstawienia_Container_ContainerWifi,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ScreenUstawienia_Label_LabelUstawienia = lv_label_create(ui_ScreenUstawienia_Container_ContainerWifi);
    lv_obj_set_width(ui_ScreenUstawienia_Label_LabelUstawienia, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScreenUstawienia_Label_LabelUstawienia, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_ScreenUstawienia_Label_LabelUstawienia, "Ustawienia WiFi");

    ui_ScreenUstawienia_Textarea_TextAreaPassword = lv_textarea_create(ui_ScreenUstawienia_Container_ContainerWifi);
    lv_obj_set_width(ui_ScreenUstawienia_Textarea_TextAreaPassword, 150);
    lv_obj_set_height(ui_ScreenUstawienia_Textarea_TextAreaPassword, 40);
    lv_obj_set_x(ui_ScreenUstawienia_Textarea_TextAreaPassword, 0);
    lv_obj_set_y(ui_ScreenUstawienia_Textarea_TextAreaPassword, 70);
    lv_textarea_set_text(ui_ScreenUstawienia_Textarea_TextAreaPassword, "Masterform!2021");
    lv_textarea_set_placeholder_text(ui_ScreenUstawienia_Textarea_TextAreaPassword, "Wifi Password");
    lv_textarea_set_password_mode(ui_ScreenUstawienia_Textarea_TextAreaPassword, true);

    ui_ScreenUstawienia_Textarea_TextAreaSSID = lv_textarea_create(ui_ScreenUstawienia_Container_ContainerWifi);
    lv_obj_set_width(ui_ScreenUstawienia_Textarea_TextAreaSSID, 150);
    lv_obj_set_height(ui_ScreenUstawienia_Textarea_TextAreaSSID, 40);
    lv_obj_set_x(ui_ScreenUstawienia_Textarea_TextAreaSSID, 0);
    lv_obj_set_y(ui_ScreenUstawienia_Textarea_TextAreaSSID, 20);
    lv_textarea_set_text(ui_ScreenUstawienia_Textarea_TextAreaSSID, "MasterformIOT");
    lv_textarea_set_placeholder_text(ui_ScreenUstawienia_Textarea_TextAreaSSID, "SSID");

    ui_ScreenUstawienia_Button_ButtonConnect = lv_btn_create(ui_ScreenUstawienia_Container_ContainerWifi);
    lv_obj_set_width(ui_ScreenUstawienia_Button_ButtonConnect, 100);
    lv_obj_set_height(ui_ScreenUstawienia_Button_ButtonConnect, 31);
    lv_obj_set_x(ui_ScreenUstawienia_Button_ButtonConnect, 40);
    lv_obj_set_y(ui_ScreenUstawienia_Button_ButtonConnect, 120);
    lv_obj_add_flag(ui_ScreenUstawienia_Button_ButtonConnect, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ScreenUstawienia_Button_ButtonConnect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ScreenUstawienia_Label_LabelConnect = lv_label_create(ui_ScreenUstawienia_Button_ButtonConnect);
    lv_obj_set_width(ui_ScreenUstawienia_Label_LabelConnect, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScreenUstawienia_Label_LabelConnect, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ScreenUstawienia_Label_LabelConnect, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScreenUstawienia_Label_LabelConnect, "Polacz");

    ui_ScreenUstawienia_Container_ContainerMQTT = lv_obj_create(ui_Screen_ScreenUstawienia);
    lv_obj_remove_style_all(ui_ScreenUstawienia_Container_ContainerMQTT);
    lv_obj_set_width(ui_ScreenUstawienia_Container_ContainerMQTT, 200);
    lv_obj_set_height(ui_ScreenUstawienia_Container_ContainerMQTT, 215);
    lv_obj_set_x(ui_ScreenUstawienia_Container_ContainerMQTT, 200);
    lv_obj_set_y(ui_ScreenUstawienia_Container_ContainerMQTT, 10);
    lv_obj_clear_flag(ui_ScreenUstawienia_Container_ContainerMQTT,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ScreenUstawienia_Label_LabelBrokerMQTT = lv_label_create(ui_ScreenUstawienia_Container_ContainerMQTT);
    lv_obj_set_width(ui_ScreenUstawienia_Label_LabelBrokerMQTT, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScreenUstawienia_Label_LabelBrokerMQTT, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_ScreenUstawienia_Label_LabelBrokerMQTT, "Broker MQTT");

    ui_ScreenUstawienia_Textarea_TextAdressMQTT = lv_textarea_create(ui_ScreenUstawienia_Container_ContainerMQTT);
    lv_obj_set_width(ui_ScreenUstawienia_Textarea_TextAdressMQTT, 180);
    lv_obj_set_height(ui_ScreenUstawienia_Textarea_TextAdressMQTT, 40);
    lv_obj_set_x(ui_ScreenUstawienia_Textarea_TextAdressMQTT, 0);
    lv_obj_set_y(ui_ScreenUstawienia_Textarea_TextAdressMQTT, 20);
    lv_textarea_set_text(ui_ScreenUstawienia_Textarea_TextAdressMQTT, "broker.hivemq.com");
    lv_textarea_set_placeholder_text(ui_ScreenUstawienia_Textarea_TextAdressMQTT, "MQTT Address");

    ui_ScreenUstawienia_Textarea_TextMQTTPort = lv_textarea_create(ui_ScreenUstawienia_Container_ContainerMQTT);
    lv_obj_set_width(ui_ScreenUstawienia_Textarea_TextMQTTPort, 80);
    lv_obj_set_height(ui_ScreenUstawienia_Textarea_TextMQTTPort, 40);
    lv_obj_set_x(ui_ScreenUstawienia_Textarea_TextMQTTPort, 0);
    lv_obj_set_y(ui_ScreenUstawienia_Textarea_TextMQTTPort, 70);
    lv_textarea_set_text(ui_ScreenUstawienia_Textarea_TextMQTTPort, "1883");
    lv_textarea_set_placeholder_text(ui_ScreenUstawienia_Textarea_TextMQTTPort, "MQTT Port");

    ui_ScreenUstawienia_Textarea_TextMQTTUser = lv_textarea_create(ui_ScreenUstawienia_Container_ContainerMQTT);
    lv_obj_set_width(ui_ScreenUstawienia_Textarea_TextMQTTUser, 150);
    lv_obj_set_height(ui_ScreenUstawienia_Textarea_TextMQTTUser, 40);
    lv_obj_set_x(ui_ScreenUstawienia_Textarea_TextMQTTUser, 0);
    lv_obj_set_y(ui_ScreenUstawienia_Textarea_TextMQTTUser, 120);
    lv_textarea_set_placeholder_text(ui_ScreenUstawienia_Textarea_TextMQTTUser, "MQTT User");

    ui_ScreenUstawienia_Textarea_TextMQTTPassword = lv_textarea_create(ui_ScreenUstawienia_Container_ContainerMQTT);
    lv_obj_set_width(ui_ScreenUstawienia_Textarea_TextMQTTPassword, 150);
    lv_obj_set_height(ui_ScreenUstawienia_Textarea_TextMQTTPassword, 40);
    lv_obj_set_x(ui_ScreenUstawienia_Textarea_TextMQTTPassword, 0);
    lv_obj_set_y(ui_ScreenUstawienia_Textarea_TextMQTTPassword, 170);
    lv_textarea_set_placeholder_text(ui_ScreenUstawienia_Textarea_TextMQTTPassword, "MQTT Password");
    lv_textarea_set_password_mode(ui_ScreenUstawienia_Textarea_TextMQTTPassword, true);

    ui_ScreenUstawienia_Container_ContainerStanowisko = lv_obj_create(ui_Screen_ScreenUstawienia);
    lv_obj_remove_style_all(ui_ScreenUstawienia_Container_ContainerStanowisko);
    lv_obj_set_width(ui_ScreenUstawienia_Container_ContainerStanowisko, 155);
    lv_obj_set_height(ui_ScreenUstawienia_Container_ContainerStanowisko, 100);
    lv_obj_set_x(ui_ScreenUstawienia_Container_ContainerStanowisko, 10);
    lv_obj_set_y(ui_ScreenUstawienia_Container_ContainerStanowisko, -10);
    lv_obj_set_align(ui_ScreenUstawienia_Container_ContainerStanowisko, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_ScreenUstawienia_Container_ContainerStanowisko,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);    /// Flags

    ui_ScreenUstawienia_Label_LabelStanowisko = lv_label_create(ui_ScreenUstawienia_Container_ContainerStanowisko);
    lv_obj_set_width(ui_ScreenUstawienia_Label_LabelStanowisko, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScreenUstawienia_Label_LabelStanowisko, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ScreenUstawienia_Label_LabelStanowisko, 10);
    lv_obj_set_y(ui_ScreenUstawienia_Label_LabelStanowisko, 0);
    lv_label_set_text(ui_ScreenUstawienia_Label_LabelStanowisko, "Stanowisko");

    ui_ScreenUstawienia_Textarea_TextAreaStanowisko = lv_textarea_create(ui_ScreenUstawienia_Container_ContainerStanowisko);
    lv_obj_set_width(ui_ScreenUstawienia_Textarea_TextAreaStanowisko, 120);
    lv_obj_set_height(ui_ScreenUstawienia_Textarea_TextAreaStanowisko, 40);
    lv_obj_set_x(ui_ScreenUstawienia_Textarea_TextAreaStanowisko, 0);
    lv_obj_set_y(ui_ScreenUstawienia_Textarea_TextAreaStanowisko, 20);
    lv_textarea_set_text(ui_ScreenUstawienia_Textarea_TextAreaStanowisko, "T3601");
    lv_textarea_set_placeholder_text(ui_ScreenUstawienia_Textarea_TextAreaStanowisko, "Placeholder...");

    ui_ScreenUstawienia_Keyboard_KeyboardUstawienia = lv_keyboard_create(ui_Screen_ScreenUstawienia);
    lv_obj_set_width(ui_ScreenUstawienia_Keyboard_KeyboardUstawienia, lv_pct(100));
    lv_obj_set_height(ui_ScreenUstawienia_Keyboard_KeyboardUstawienia, lv_pct(60));
    lv_obj_set_align(ui_ScreenUstawienia_Keyboard_KeyboardUstawienia, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_ScreenUstawienia_Keyboard_KeyboardUstawienia, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_bg_color(ui_ScreenUstawienia_Keyboard_KeyboardUstawienia, lv_color_hex(0x3C3C3C),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenUstawienia_Keyboard_KeyboardUstawienia, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ScreenUstawienia_Button_ButtonChangeScreen1,
                        ui_event_ScreenUstawienia_Button_ButtonChangeScreen1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScreenUstawienia_Textarea_TextAreaPassword, ui_event_ScreenUstawienia_Textarea_TextAreaPassword,
                        LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScreenUstawienia_Textarea_TextAreaSSID, ui_event_ScreenUstawienia_Textarea_TextAreaSSID,
                        LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScreenUstawienia_Textarea_TextAdressMQTT, ui_event_ScreenUstawienia_Textarea_TextAdressMQTT,
                        LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScreenUstawienia_Textarea_TextMQTTPort, ui_event_ScreenUstawienia_Textarea_TextMQTTPort,
                        LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScreenUstawienia_Textarea_TextMQTTUser, ui_event_ScreenUstawienia_Textarea_TextMQTTUser,
                        LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScreenUstawienia_Textarea_TextMQTTPassword, ui_event_ScreenUstawienia_Textarea_TextMQTTPassword,
                        LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScreenUstawienia_Textarea_TextAreaStanowisko,
                        ui_event_ScreenUstawienia_Textarea_TextAreaStanowisko, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScreenUstawienia_Keyboard_KeyboardUstawienia,
                        ui_event_ScreenUstawienia_Keyboard_KeyboardUstawienia, LV_EVENT_ALL, NULL);

}
