// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen_ScreenPraca_screen_init(void)
{
    ui_Screen_ScreenPraca = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen_ScreenPraca, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen_ScreenPraca, lv_color_hex(0x787878), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen_ScreenPraca, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScreenPraca_Panel_PanelViolet = lv_obj_create(ui_Screen_ScreenPraca);
    lv_obj_set_width(ui_ScreenPraca_Panel_PanelViolet, lv_pct(95));
    lv_obj_set_height(ui_ScreenPraca_Panel_PanelViolet, lv_pct(95));
    lv_obj_set_align(ui_ScreenPraca_Panel_PanelViolet, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ScreenPraca_Panel_PanelViolet, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_ScreenPraca_Panel_PanelViolet, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenPraca_Panel_PanelViolet, lv_color_hex(0x960096), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenPraca_Panel_PanelViolet, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScreenPraca_Panel_PanelBlue = lv_obj_create(ui_Screen_ScreenPraca);
    lv_obj_set_width(ui_ScreenPraca_Panel_PanelBlue, lv_pct(95));
    lv_obj_set_height(ui_ScreenPraca_Panel_PanelBlue, lv_pct(95));
    lv_obj_set_align(ui_ScreenPraca_Panel_PanelBlue, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ScreenPraca_Panel_PanelBlue, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_ScreenPraca_Panel_PanelBlue, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenPraca_Panel_PanelBlue, lv_color_hex(0x000096), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenPraca_Panel_PanelBlue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScreenPraca_Panel_PanelRed = lv_obj_create(ui_Screen_ScreenPraca);
    lv_obj_set_width(ui_ScreenPraca_Panel_PanelRed, lv_pct(95));
    lv_obj_set_height(ui_ScreenPraca_Panel_PanelRed, lv_pct(95));
    lv_obj_set_align(ui_ScreenPraca_Panel_PanelRed, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ScreenPraca_Panel_PanelRed, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_ScreenPraca_Panel_PanelRed, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenPraca_Panel_PanelRed, lv_color_hex(0x960000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenPraca_Panel_PanelRed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScreenPraca_Panel_PanelGreen = lv_obj_create(ui_Screen_ScreenPraca);
    lv_obj_set_width(ui_ScreenPraca_Panel_PanelGreen, lv_pct(95));
    lv_obj_set_height(ui_ScreenPraca_Panel_PanelGreen, lv_pct(95));
    lv_obj_set_align(ui_ScreenPraca_Panel_PanelGreen, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ScreenPraca_Panel_PanelGreen, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_ScreenPraca_Panel_PanelGreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenPraca_Panel_PanelGreen, lv_color_hex(0x009600), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenPraca_Panel_PanelGreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScreenPraca_Panel_PanelYellow = lv_obj_create(ui_Screen_ScreenPraca);
    lv_obj_set_width(ui_ScreenPraca_Panel_PanelYellow, lv_pct(95));
    lv_obj_set_height(ui_ScreenPraca_Panel_PanelYellow, lv_pct(95));
    lv_obj_set_align(ui_ScreenPraca_Panel_PanelYellow, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ScreenPraca_Panel_PanelYellow, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_ScreenPraca_Panel_PanelYellow, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenPraca_Panel_PanelYellow, lv_color_hex(0xDCB400), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenPraca_Panel_PanelYellow, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScreenPraca_Dropdown_DropdownStatus = lv_dropdown_create(ui_Screen_ScreenPraca);
    lv_dropdown_set_options(ui_ScreenPraca_Dropdown_DropdownStatus,
                            "Brak Obsady\nPraca\nAwaria\nPomiar\nPrzezbrojenie\nPrzerwa\n");
    lv_obj_set_width(ui_ScreenPraca_Dropdown_DropdownStatus, 150);
    lv_obj_set_height(ui_ScreenPraca_Dropdown_DropdownStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ScreenPraca_Dropdown_DropdownStatus, 55);
    lv_obj_set_y(ui_ScreenPraca_Dropdown_DropdownStatus, 120);
    lv_obj_set_align(ui_ScreenPraca_Dropdown_DropdownStatus, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ScreenPraca_Dropdown_DropdownStatus, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ScreenPraca_Dropdown_DropdownStatus,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags

    ui_ScreenPraca_Container_Container1 = lv_obj_create(ui_Screen_ScreenPraca);
    lv_obj_remove_style_all(ui_ScreenPraca_Container_Container1);
    lv_obj_set_width(ui_ScreenPraca_Container_Container1, 200);
    lv_obj_set_height(ui_ScreenPraca_Container_Container1, lv_pct(95));
    lv_obj_set_y(ui_ScreenPraca_Container_Container1, 0);
    lv_obj_set_x(ui_ScreenPraca_Container_Container1, lv_pct(3));
    lv_obj_set_align(ui_ScreenPraca_Container_Container1, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_ScreenPraca_Container_Container1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ScreenPraca_Container_Container1, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_START,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ScreenPraca_Container_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ScreenPraca_Button_BtnPraca = lv_btn_create(ui_ScreenPraca_Container_Container1);
    lv_obj_set_width(ui_ScreenPraca_Button_BtnPraca, 180);
    lv_obj_set_height(ui_ScreenPraca_Button_BtnPraca, 40);
    lv_obj_set_x(ui_ScreenPraca_Button_BtnPraca, lv_pct(5));
    lv_obj_set_y(ui_ScreenPraca_Button_BtnPraca, lv_pct(5));
    lv_obj_add_flag(ui_ScreenPraca_Button_BtnPraca, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ScreenPraca_Button_BtnPraca, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenPraca_Button_BtnPraca, lv_color_hex(0x005000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenPraca_Button_BtnPraca, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ScreenPraca_Button_BtnPraca, lv_color_hex(0x007800), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ScreenPraca_Button_BtnPraca, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ScreenPraca_Button_BtnPraca, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ScreenPraca_Button_BtnPraca, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ScreenPraca_Button_BtnPraca, 10, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_color(ui_ScreenPraca_Button_BtnPraca, lv_color_hex(0xFAFAFA), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_opa(ui_ScreenPraca_Button_BtnPraca, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_width(ui_ScreenPraca_Button_BtnPraca, 2, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_ScreenPraca_Label_LabPrc = lv_label_create(ui_ScreenPraca_Button_BtnPraca);
    lv_obj_set_width(ui_ScreenPraca_Label_LabPrc, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScreenPraca_Label_LabPrc, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ScreenPraca_Label_LabPrc, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_ScreenPraca_Label_LabPrc, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_ScreenPraca_Label_LabPrc, "Praca");
    lv_obj_set_style_text_font(ui_ScreenPraca_Label_LabPrc, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScreenPraca_Button_BtnAwaria = lv_btn_create(ui_ScreenPraca_Container_Container1);
    lv_obj_set_width(ui_ScreenPraca_Button_BtnAwaria, 180);
    lv_obj_set_height(ui_ScreenPraca_Button_BtnAwaria, 40);
    lv_obj_set_x(ui_ScreenPraca_Button_BtnAwaria, lv_pct(5));
    lv_obj_set_y(ui_ScreenPraca_Button_BtnAwaria, lv_pct(5));
    lv_obj_add_flag(ui_ScreenPraca_Button_BtnAwaria, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ScreenPraca_Button_BtnAwaria,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_bg_color(ui_ScreenPraca_Button_BtnAwaria, lv_color_hex(0x780000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenPraca_Button_BtnAwaria, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ScreenPraca_Button_BtnAwaria, lv_color_hex(0xB40000),
                                   LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ScreenPraca_Button_BtnAwaria, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ScreenPraca_Button_BtnAwaria, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ScreenPraca_Button_BtnAwaria, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ScreenPraca_Button_BtnAwaria, 10, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_color(ui_ScreenPraca_Button_BtnAwaria, lv_color_hex(0xFAFAFA), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_opa(ui_ScreenPraca_Button_BtnAwaria, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_width(ui_ScreenPraca_Button_BtnAwaria, 2, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_ScreenPraca_Label_LabAwaria = lv_label_create(ui_ScreenPraca_Button_BtnAwaria);
    lv_obj_set_width(ui_ScreenPraca_Label_LabAwaria, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScreenPraca_Label_LabAwaria, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ScreenPraca_Label_LabAwaria, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_ScreenPraca_Label_LabAwaria, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_ScreenPraca_Label_LabAwaria, "Awaria");
    lv_obj_set_style_text_font(ui_ScreenPraca_Label_LabAwaria, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScreenPraca_Button_BtnPomiar = lv_btn_create(ui_ScreenPraca_Container_Container1);
    lv_obj_set_width(ui_ScreenPraca_Button_BtnPomiar, 180);
    lv_obj_set_height(ui_ScreenPraca_Button_BtnPomiar, 40);
    lv_obj_set_x(ui_ScreenPraca_Button_BtnPomiar, lv_pct(5));
    lv_obj_set_y(ui_ScreenPraca_Button_BtnPomiar, lv_pct(5));
    lv_obj_add_flag(ui_ScreenPraca_Button_BtnPomiar, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ScreenPraca_Button_BtnPomiar,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_bg_color(ui_ScreenPraca_Button_BtnPomiar, lv_color_hex(0x000050), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenPraca_Button_BtnPomiar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ScreenPraca_Button_BtnPomiar, lv_color_hex(0x0000AA),
                                   LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ScreenPraca_Button_BtnPomiar, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ScreenPraca_Button_BtnPomiar, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ScreenPraca_Button_BtnPomiar, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ScreenPraca_Button_BtnPomiar, 10, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_color(ui_ScreenPraca_Button_BtnPomiar, lv_color_hex(0xFAFAFA), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_opa(ui_ScreenPraca_Button_BtnPomiar, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_width(ui_ScreenPraca_Button_BtnPomiar, 2, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_ScreenPraca_Label_LabPomiar = lv_label_create(ui_ScreenPraca_Button_BtnPomiar);
    lv_obj_set_width(ui_ScreenPraca_Label_LabPomiar, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScreenPraca_Label_LabPomiar, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ScreenPraca_Label_LabPomiar, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_ScreenPraca_Label_LabPomiar, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_ScreenPraca_Label_LabPomiar, "Pomiar");
    lv_obj_set_style_text_font(ui_ScreenPraca_Label_LabPomiar, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScreenPraca_Button_BtnPrzezbrojenie = lv_btn_create(ui_ScreenPraca_Container_Container1);
    lv_obj_set_width(ui_ScreenPraca_Button_BtnPrzezbrojenie, 180);
    lv_obj_set_height(ui_ScreenPraca_Button_BtnPrzezbrojenie, 40);
    lv_obj_set_x(ui_ScreenPraca_Button_BtnPrzezbrojenie, lv_pct(5));
    lv_obj_set_y(ui_ScreenPraca_Button_BtnPrzezbrojenie, lv_pct(5));
    lv_obj_add_flag(ui_ScreenPraca_Button_BtnPrzezbrojenie, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ScreenPraca_Button_BtnPrzezbrojenie,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_bg_color(ui_ScreenPraca_Button_BtnPrzezbrojenie, lv_color_hex(0x500050),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenPraca_Button_BtnPrzezbrojenie, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ScreenPraca_Button_BtnPrzezbrojenie, lv_color_hex(0x780078),
                                   LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ScreenPraca_Button_BtnPrzezbrojenie, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ScreenPraca_Button_BtnPrzezbrojenie, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ScreenPraca_Button_BtnPrzezbrojenie, LV_BORDER_SIDE_FULL,
                                 LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ScreenPraca_Button_BtnPrzezbrojenie, 10, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_color(ui_ScreenPraca_Button_BtnPrzezbrojenie, lv_color_hex(0xFAFAFA),
                                  LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_opa(ui_ScreenPraca_Button_BtnPrzezbrojenie, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_width(ui_ScreenPraca_Button_BtnPrzezbrojenie, 2, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_ScreenPraca_Label_LabPrzezbrojenie = lv_label_create(ui_ScreenPraca_Button_BtnPrzezbrojenie);
    lv_obj_set_width(ui_ScreenPraca_Label_LabPrzezbrojenie, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScreenPraca_Label_LabPrzezbrojenie, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ScreenPraca_Label_LabPrzezbrojenie, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_ScreenPraca_Label_LabPrzezbrojenie, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_ScreenPraca_Label_LabPrzezbrojenie, "Przezbrojenie");
    lv_obj_set_style_text_font(ui_ScreenPraca_Label_LabPrzezbrojenie, &lv_font_montserrat_20,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScreenPraca_Button_BtnPrzerwa = lv_btn_create(ui_ScreenPraca_Container_Container1);
    lv_obj_set_width(ui_ScreenPraca_Button_BtnPrzerwa, 180);
    lv_obj_set_height(ui_ScreenPraca_Button_BtnPrzerwa, 40);
    lv_obj_set_x(ui_ScreenPraca_Button_BtnPrzerwa, lv_pct(5));
    lv_obj_set_y(ui_ScreenPraca_Button_BtnPrzerwa, lv_pct(5));
    lv_obj_add_flag(ui_ScreenPraca_Button_BtnPrzerwa, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ScreenPraca_Button_BtnPrzerwa,
                      LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenPraca_Button_BtnPrzerwa, lv_color_hex(0xC8A000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenPraca_Button_BtnPrzerwa, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ScreenPraca_Button_BtnPrzerwa, lv_color_hex(0xDCB400),
                                   LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ScreenPraca_Button_BtnPrzerwa, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ScreenPraca_Button_BtnPrzerwa, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ScreenPraca_Button_BtnPrzerwa, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ScreenPraca_Button_BtnPrzerwa, 10, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_color(ui_ScreenPraca_Button_BtnPrzerwa, lv_color_hex(0xFAFAFA),
                                  LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_opa(ui_ScreenPraca_Button_BtnPrzerwa, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_width(ui_ScreenPraca_Button_BtnPrzerwa, 2, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_ScreenPraca_Label_LabPrc1 = lv_label_create(ui_ScreenPraca_Button_BtnPrzerwa);
    lv_obj_set_width(ui_ScreenPraca_Label_LabPrc1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScreenPraca_Label_LabPrc1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ScreenPraca_Label_LabPrc1, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_ScreenPraca_Label_LabPrc1, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_ScreenPraca_Label_LabPrc1, "Przerwa");
    lv_obj_set_style_text_font(ui_ScreenPraca_Label_LabPrc1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScreenPraca_Button_BtnBrakObsdy = lv_btn_create(ui_ScreenPraca_Container_Container1);
    lv_obj_set_width(ui_ScreenPraca_Button_BtnBrakObsdy, 180);
    lv_obj_set_height(ui_ScreenPraca_Button_BtnBrakObsdy, 40);
    lv_obj_set_x(ui_ScreenPraca_Button_BtnBrakObsdy, lv_pct(5));
    lv_obj_set_y(ui_ScreenPraca_Button_BtnBrakObsdy, lv_pct(5));
    lv_obj_add_flag(ui_ScreenPraca_Button_BtnBrakObsdy, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ScreenPraca_Button_BtnBrakObsdy,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_bg_color(ui_ScreenPraca_Button_BtnBrakObsdy, lv_color_hex(0x505050), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenPraca_Button_BtnBrakObsdy, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ScreenPraca_Button_BtnBrakObsdy, lv_color_hex(0x787878),
                                   LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ScreenPraca_Button_BtnBrakObsdy, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ScreenPraca_Button_BtnBrakObsdy, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ScreenPraca_Button_BtnBrakObsdy, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ScreenPraca_Button_BtnBrakObsdy, 10, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_color(ui_ScreenPraca_Button_BtnBrakObsdy, lv_color_hex(0xFAFAFA),
                                  LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_opa(ui_ScreenPraca_Button_BtnBrakObsdy, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_width(ui_ScreenPraca_Button_BtnBrakObsdy, 2, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_ScreenPraca_Label_LabBrakObsady = lv_label_create(ui_ScreenPraca_Button_BtnBrakObsdy);
    lv_obj_set_width(ui_ScreenPraca_Label_LabBrakObsady, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScreenPraca_Label_LabBrakObsady, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ScreenPraca_Label_LabBrakObsady, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_ScreenPraca_Label_LabBrakObsady, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_ScreenPraca_Label_LabBrakObsady, "Brak Obsady");
    lv_obj_set_style_text_font(ui_ScreenPraca_Label_LabBrakObsady, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScreenPraca_Textarea_EdOperator = lv_textarea_create(ui_Screen_ScreenPraca);
    lv_obj_set_width(ui_ScreenPraca_Textarea_EdOperator, 145);
    lv_obj_set_height(ui_ScreenPraca_Textarea_EdOperator, 40);
    lv_obj_set_x(ui_ScreenPraca_Textarea_EdOperator, 145);
    lv_obj_set_y(ui_ScreenPraca_Textarea_EdOperator, -120);
    lv_obj_set_align(ui_ScreenPraca_Textarea_EdOperator, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_ScreenPraca_Textarea_EdOperator, 5);
    lv_textarea_set_placeholder_text(ui_ScreenPraca_Textarea_EdOperator, "Operator");

    ui_ScreenPraca_Keyboard_KeybOperator = lv_keyboard_create(ui_Screen_ScreenPraca);
    lv_keyboard_set_mode(ui_ScreenPraca_Keyboard_KeybOperator, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_ScreenPraca_Keyboard_KeybOperator, lv_pct(45));
    lv_obj_set_height(ui_ScreenPraca_Keyboard_KeybOperator, lv_pct(80));
    lv_obj_set_x(ui_ScreenPraca_Keyboard_KeybOperator, lv_pct(25));
    lv_obj_set_y(ui_ScreenPraca_Keyboard_KeybOperator, lv_pct(8));
    lv_obj_set_align(ui_ScreenPraca_Keyboard_KeybOperator, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ScreenPraca_Keyboard_KeybOperator, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_ScreenPraca_Keyboard_KeybOperator, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenPraca_Keyboard_KeybOperator, lv_color_hex(0x969696),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenPraca_Keyboard_KeybOperator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_ScreenPraca_Keyboard_KeybOperator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScreenPraca_Keyboard_KeybOperator, lv_color_hex(0x969696),
                              LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_ScreenPraca_Keyboard_KeybOperator, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_opa(ui_ScreenPraca_Keyboard_KeybOperator, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_opa(ui_ScreenPraca_Keyboard_KeybOperator, 255, LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_FOCUSED);

    ui_ScreenPraca_Button_ButtonChangeScreen = lv_btn_create(ui_Screen_ScreenPraca);
    lv_obj_set_width(ui_ScreenPraca_Button_ButtonChangeScreen, 50);
    lv_obj_set_height(ui_ScreenPraca_Button_ButtonChangeScreen, 50);
    lv_obj_set_x(ui_ScreenPraca_Button_ButtonChangeScreen, 210);
    lv_obj_set_y(ui_ScreenPraca_Button_ButtonChangeScreen, 130);
    lv_obj_set_align(ui_ScreenPraca_Button_ButtonChangeScreen, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ScreenPraca_Button_ButtonChangeScreen,
                    LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ScreenPraca_Button_ButtonChangeScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ScreenPraca_Textarea_TextArea1 = lv_textarea_create(ui_Screen_ScreenPraca);
    lv_obj_set_width(ui_ScreenPraca_Textarea_TextArea1, 90);
    lv_obj_set_height(ui_ScreenPraca_Textarea_TextArea1, 40);
    lv_obj_set_x(ui_ScreenPraca_Textarea_TextArea1, 20);
    lv_obj_set_y(ui_ScreenPraca_Textarea_TextArea1, -120);
    lv_obj_set_align(ui_ScreenPraca_Textarea_TextArea1, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_ScreenPraca_Textarea_TextArea1, "00:00:00");

    ui_ScreenPraca_Textarea_TextMQTTData = lv_textarea_create(ui_Screen_ScreenPraca);
    lv_obj_set_height(ui_ScreenPraca_Textarea_TextMQTTData, 40);
    lv_obj_set_width(ui_ScreenPraca_Textarea_TextMQTTData, lv_pct(50));
    lv_obj_set_x(ui_ScreenPraca_Textarea_TextMQTTData, 217);
    lv_obj_set_y(ui_ScreenPraca_Textarea_TextMQTTData, 135);
    lv_textarea_set_placeholder_text(ui_ScreenPraca_Textarea_TextMQTTData, "data");

    lv_obj_add_event_cb(ui_ScreenPraca_Button_BtnPraca, ui_event_ScreenPraca_Button_BtnPraca, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScreenPraca_Button_BtnAwaria, ui_event_ScreenPraca_Button_BtnAwaria, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScreenPraca_Button_BtnPomiar, ui_event_ScreenPraca_Button_BtnPomiar, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScreenPraca_Button_BtnPrzezbrojenie, ui_event_ScreenPraca_Button_BtnPrzezbrojenie, LV_EVENT_ALL,
                        NULL);
    lv_obj_add_event_cb(ui_ScreenPraca_Button_BtnPrzerwa, ui_event_ScreenPraca_Button_BtnPrzerwa, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScreenPraca_Label_LabBrakObsady, ui_event_ScreenPraca_Label_LabBrakObsady, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScreenPraca_Button_BtnBrakObsdy, ui_event_ScreenPraca_Button_BtnBrakObsdy, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScreenPraca_Textarea_EdOperator, ui_event_ScreenPraca_Textarea_EdOperator, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_ScreenPraca_Keyboard_KeybOperator, ui_ScreenPraca_Textarea_EdOperator);
    lv_obj_add_event_cb(ui_ScreenPraca_Keyboard_KeybOperator, ui_event_ScreenPraca_Keyboard_KeybOperator, LV_EVENT_ALL,
                        NULL);
    lv_obj_add_event_cb(ui_Screen_ScreenPraca, ui_event_Screen_ScreenPraca, LV_EVENT_ALL, NULL);
    uic_PanelYellow = ui_ScreenPraca_Panel_PanelYellow;
    uic_BtnPraca = ui_ScreenPraca_Button_BtnPraca;
    uic_BtnPrzerwa = ui_ScreenPraca_Button_BtnPrzerwa;

}
